[package]
# name = "foto-image-transformer"
name = "foto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
serde_json = "1.0.74"
regex = "1"